post_tiltes = ["SurrealEngine: Open-source reimplementation of Unreal Engine with playable UT99",
"Launch HN: Moonglow (YC S24) – Serverless Jupyter Notebooks",
"Cautionary tale on using Chase bank for indie business",
"OpenSSH Backdoors",
"Nanolog supports logging with 7 ns median latency",
"Vega – A declarative language for interactive visualization designs",
"We need to liberate the Postcode Address File",
"17-Year-Old Student Exposes Germany's 'Secret' Pirate Site Blocklist",
"SnapDiagram – Instantly Convert Hand-Drawn Diagrams to Digital with AI",
"Show HN: AI Tool Is Now Supporting React, Angular, CSS, Svelte, Vue",
"Playing Sudoku in TypeScript while the type checker highlights mistakes",
"TextBundle",
"Show HN: Ruroco – like port knocking, but better",
"DOJ Sues RealPage for Algorithmic Pricing Scheme That Harms Renters",
"Confessions of a Theoretical Physicist",
"Claude's API now supports CORS requests, enabling client-side applications",
"Optimisation-dependent IR decisions in Clang",
"EPUBCheck – The official conformance checker for ePub publications",
"Pierre Cartier Has Died",
"The staggering death toll of scientific lies",
"Python’s Preprocessor",
"Show HN: InstantDB – A Modern Firebase",
"Tales from the Far Side",
"Evidence stacks up for poisonous books containing toxic dyes",
"AI photo editing raises trust issues in photography",
"Surfer: Centralize all your personal data from online platforms",
"The Chancellor's Excellent Questions",
"Hacker Purity Test (1989)",
"We don't know how bad most things are nor precisely how they're bad",
"Continuous reinvention: A brief history of block storage at AWS"]